# Generated by Django 4.2.5 on 2023-11-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='myimages'),
        ),
    ]
